import type { LabelObject } from "../types/Group";

export const testModels: Record<string, LabelObject> = {
  barcode_code128_standard: {
    id: "1",
    type: "code128",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "123456",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_code128_small_no_text: {
    id: "2",
    type: "code128",
    x: 100,
    y: 100,
    rotation: 0,
    props: {
      content: "TEST",
      height: 50,
      moduleWidth: 1,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_code128_large_check_digit: {
    id: "3",
    type: "code128",
    x: 20,
    y: 20,
    rotation: 0,
    props: {
      content: "98765",
      height: 150,
      moduleWidth: 3,
      printInterpretation: false,
      checkDigit: true,
      rotation: "N",
    },
  },
  barcode_qr_standard: {
    id: "4",
    type: "qrcode",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "Hello World", magnification: 4, errorCorrection: "Q", rotation: "N" },
  },
  barcode_qr_large_high_ec: {
    id: "5",
    type: "qrcode",
    x: 150,
    y: 150,
    rotation: 0,
    props: {
      content: "Zebra Print Lab QR Code Testing",
      magnification: 8,
      errorCorrection: "H",
      rotation: "N",
    },
  },
  barcode_ean13_standard: {
    id: "6",
    type: "ean13",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "123456789012",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_datamatrix_standard: {
    id: "7",
    type: "datamatrix",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "DataMatrixTest", dimension: 5, quality: 200, rotation: "N" },
  },
  barcode_code39_standard: {
    id: "8",
    type: "code39",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "CODE39",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_pdf417_standard: {
    id: "9",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 10,
      securityLevel: 1,
      columns: 4,
      moduleWidth: 2,
      rotation: "N",
    },
  },
  barcode_upca_standard: {
    id: "10",
    type: "upca",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "01234567890",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_ean8_standard: {
    id: "11",
    type: "ean8",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_aztec_standard: {
    id: "12",
    type: "aztec",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "Aztec123", magnification: 4, ecLevel: 0, rotation: "N" },
  },
  barcode_interleaved2of5_standard: {
    id: "13",
    type: "interleaved2of5",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "12345678",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
      rotation: "N",
    },
  },
  barcode_micropdf417_standard: {
    id: "14",
    type: "micropdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234",
      moduleWidth: 2,
      rowHeight: 2,
      mode: 0,
      rotation: "N",
    },
  },
  barcode_codablock_standard: {
    id: "15",
    type: "codablock",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      moduleWidth: 2,
      rowHeight: 2,
      securityLevel: "Y",
      rotation: "N",
    },
  },
  barcode_pdf417_auto: {
    id: "16",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 10,
      securityLevel: 1,
      columns: 0,
      moduleWidth: 2,
      rotation: "N",
    },
  },
  barcode_pdf417_auto_ecc: {
    id: "17",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 4,
      securityLevel: 0,
      columns: 0,
      moduleWidth: 2,
      rotation: "N",
    },
  },
  barcode_code93_standard: {
    id: "18",
    type: "code93",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "CODE93", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_code11_standard: {
    id: "19",
    type: "code11",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_industrial2of5_standard: {
    id: "20",
    type: "industrial2of5",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345678", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_standard2of5_standard: {
    id: "21",
    type: "standard2of5",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345678", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_codabar_standard: {
    id: "22",
    type: "codabar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "A12345A", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_logmars_standard: {
    id: "23",
    type: "logmars",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "LOGMARS1", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_logmars_with_text: {
    id: "23b",
    type: "logmars",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "LOGMARS1", height: 100, moduleWidth: 2, printInterpretation: true, checkDigit: false, rotation: "N" },
  },
  barcode_msi_standard: {
    id: "24",
    type: "msi",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345678", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_plessey_standard: {
    id: "25",
    type: "plessey",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345678", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_planet_standard: {
    id: "26",
    type: "planet",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345678901", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_postal_standard: {
    id: "27",
    type: "postal",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "12345", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_gs1databar_standard: {
    id: "28",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901", magnification: 2, symbology: 1, rotation: "N" },
  },
  barcode_gs1databar_truncated: {
    id: "gs1_2",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901", magnification: 2, symbology: 2, rotation: "N" },
  },
  barcode_gs1databar_stacked: {
    id: "gs1_3",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901", magnification: 2, symbology: 3, rotation: "N" },
  },
  barcode_gs1databar_stacked_omni: {
    id: "gs1_4",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901", magnification: 2, symbology: 4, rotation: "N" },
  },
  barcode_gs1databar_limited: {
    id: "gs1_5",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901", magnification: 2, symbology: 5, rotation: "N" },
  },
  barcode_gs1databar_expanded: {
    id: "gs1_6",
    type: "gs1databar",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "0112345678901231", magnification: 2, symbology: 6, rotation: "N" },
  },
  barcode_upce_standard: {
    id: "29",
    type: "upce",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "012345", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },

  // ── Rotation coverage ───────────────────────────────────────────────────
  barcode_code128_rot_R: {
    id: "rot1",
    type: "code128",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "123456", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "R" },
  },
  barcode_code128_rot_I: {
    id: "rot2",
    type: "code128",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "123456", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "I" },
  },
  barcode_code128_rot_B: {
    id: "rot3",
    type: "code128",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "123456", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "B" },
  },
  barcode_qr_rot_R: {
    id: "rot4",
    type: "qrcode",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "Hello World", magnification: 4, errorCorrection: "Q", rotation: "R" },
  },
  barcode_datamatrix_rot_R: {
    id: "rot5",
    type: "datamatrix",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "DataMatrixTest", dimension: 5, quality: 200, rotation: "R" },
  },
  barcode_code39_rot_R: {
    id: "rot6",
    type: "code39",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "CODE39", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "R" },
  },
  barcode_code39_rot_B: {
    id: "rot7",
    type: "code39",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "CODE39", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "B" },
  },
  barcode_ean13_rot_R: {
    id: "rot8",
    type: "ean13",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "123456789012", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "R" },
  },
  barcode_ean13_rot_B: {
    id: "rot9",
    type: "ean13",
    x: 100,
    y: 100,
    rotation: 0,
    props: { content: "123456789012", height: 100, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "B" },
  },
  barcode_upcean_supp5_standard: {
    id: "supp1",
    type: "upcEanExtension",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "51999", height: 80, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
  barcode_upcean_supp2_standard: {
    id: "supp2",
    type: "upcEanExtension",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "42", height: 80, moduleWidth: 2, printInterpretation: false, checkDigit: false, rotation: "N" },
  },
};
