import type { LabelObject } from "../registry";

export const testModels: Record<string, LabelObject> = {
  barcode_code128_standard: {
    id: "1",
    type: "code128",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "123456",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_code128_small_no_text: {
    id: "2",
    type: "code128",
    x: 100,
    y: 100,
    rotation: 0,
    props: {
      content: "TEST",
      height: 50,
      moduleWidth: 1,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_code128_large_check_digit: {
    id: "3",
    type: "code128",
    x: 20,
    y: 20,
    rotation: 0,
    props: {
      content: "98765",
      height: 150,
      moduleWidth: 3,
      printInterpretation: false,
      checkDigit: true,
    },
  },
  barcode_qr_standard: {
    id: "4",
    type: "qrcode",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "Hello World", magnification: 4, errorCorrection: "Q" },
  },
  barcode_qr_large_high_ec: {
    id: "5",
    type: "qrcode",
    x: 150,
    y: 150,
    rotation: 0,
    props: {
      content: "Zebra Print Lab QR Code Testing",
      magnification: 8,
      errorCorrection: "H",
    },
  },
  barcode_ean13_standard: {
    id: "6",
    type: "ean13",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "123456789012",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
    },
  },
  barcode_datamatrix_standard: {
    id: "7",
    type: "datamatrix",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "DataMatrixTest", dimension: 5, quality: 200 },
  },
  barcode_code39_standard: {
    id: "8",
    type: "code39",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "CODE39",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_pdf417_standard: {
    id: "9",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 10,
      securityLevel: 1,
      columns: 4,
      moduleWidth: 2,
    },
  },
  barcode_upca_standard: {
    id: "10",
    type: "upca",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "01234567890",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_ean8_standard: {
    id: "11",
    type: "ean8",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_aztec_standard: {
    id: "12",
    type: "aztec",
    x: 50,
    y: 50,
    rotation: 0,
    props: { content: "Aztec123", magnification: 4, ecLevel: 0 },
  },
  barcode_interleaved2of5_standard: {
    id: "13",
    type: "interleaved2of5",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "12345678",
      height: 100,
      moduleWidth: 2,
      printInterpretation: false,
      checkDigit: false,
    },
  },
  barcode_micropdf417_standard: {
    id: "14",
    type: "micropdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234",
      moduleWidth: 2,
      rowHeight: 2,
      mode: 0,
    },
  },
  barcode_codablock_standard: {
    id: "15",
    type: "codablock",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      moduleWidth: 2,
      rowHeight: 2,
      securityLevel: "Y",
    },
  },
  barcode_pdf417_auto: {
    id: "16",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 10,
      securityLevel: 1,
      columns: 0,
      moduleWidth: 2,
    },
  },
  barcode_pdf417_auto_ecc: {
    id: "17",
    type: "pdf417",
    x: 50,
    y: 50,
    rotation: 0,
    props: {
      content: "1234567890",
      rowHeight: 4,
      securityLevel: 0,
      columns: 0,
      moduleWidth: 2,
    },
  },
};
