// Build the sidecar as a Node SEA binary: esbuild CJS bundle -> SEA blob ->
// inject into a node copy. Cross builds (CI macOS x86_64 on the arm64 runner)
// must pass --node with a downloaded target-arch node, not the runner's own.
import { execFileSync } from "node:child_process";
import { chmodSync, copyFileSync, mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

const pkgDir = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(pkgDir, "dist-sea");
const { values } = parseArgs({
  options: {
    // Node executable to clone for the target platform/arch.
    node: { type: "string", default: process.execPath },
    out: { type: "string" },
  },
});

const isWindows = process.platform === "win32";
const isMac = process.platform === "darwin";
const exeName = values.out ?? (isWindows ? "zplab-mcp.exe" : "zplab-mcp");

const run = (cmd, args) => execFileSync(cmd, args, { stdio: "inherit", cwd: pkgDir });
// Both tool bins are JS shims, so run them through node directly: no shell,
// no pnpm wrapper, works identically on every platform.
const require = createRequire(import.meta.url);
const runBin = (spec, args) => run(process.execPath, [require.resolve(spec), ...args]);

mkdirSync(outDir, { recursive: true });
const bundle = join(outDir, "zplab-mcp.cjs");
const blob = join(outDir, "zplab-mcp.blob");
const exe = join(outDir, exeName);

runBin("esbuild/bin/esbuild", [
  join(pkgDir, "src", "index.ts"),
  "--bundle",
  "--platform=node",
  "--format=cjs",
  "--minify",
  `--outfile=${bundle}`,
]);

writeFileSync(
  join(outDir, "sea-config.json"),
  JSON.stringify({ main: bundle, output: blob, disableExperimentalSEAWarning: true }),
);
run(process.execPath, ["--experimental-sea-config", join(outDir, "sea-config.json")]);

// The blob is generated by the RUNNER's node but runs inside the target
// binary; the SEA format is version-coupled, so a skew fails at runtime.
// A foreign-arch target may not be executable here (then verify manually).
if (values.node !== process.execPath) {
  let targetVersion = null;
  try {
    targetVersion = execFileSync(values.node, ["--version"]).toString().trim();
  } catch {
    console.warn(`cannot execute ${values.node}; ensure its version is ${process.version}`);
  }
  if (targetVersion !== null && targetVersion !== process.version) {
    throw new Error(`target node is ${targetVersion}, runner is ${process.version}`);
  }
}
copyFileSync(values.node, exe);
// postject invalidates the executable's signature; macOS arm64 refuses to run
// unsigned binaries, so strip before injecting and ad-hoc re-sign after (the
// release carries no OS code signing, only the Tauri updater signature).
if (isMac) run("codesign", ["--remove-signature", exe]);
runBin("postject/dist/cli.js", [
  exe,
  "NODE_SEA_BLOB",
  blob,
  "--sentinel-fuse",
  "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2",
  ...(isMac ? ["--macho-segment-name", "NODE_SEA"] : []),
]);
if (isMac) run("codesign", ["-s", "-", exe]);
if (!isWindows) chmodSync(exe, 0o755);

console.log(`built ${exe}`);
