// GENERATED from the GS1 Barcode Syntax Dictionary (GS1 AISBL, Apache-2.0,
// derived from BWIPP + Zint) via scripts/gen-gs1-catalog.mjs. Do not hand-edit.
// Data only; the entry types live in gs1AiCatalog.types.ts. Consumed by
// src/lib/gs1.ts (AI_BY_CODE), which expands ranges and skips multiComponent
// AIs (their extra fields are not modeled yet).

import type { Gs1AiCatalogEntry } from './gs1AiCatalog.types';

export const GS1_AI_FULL_CATALOG: readonly Gs1AiCatalogEntry[] = [
  { ai: '00', kind: 'fixedNum', len: 18, checkDigit: true, group: 'logistics', title: "SSCC" },
  { ai: '01', kind: 'gtin', len: 14, checkDigit: true, ex: ['255', '37'], group: 'identification', title: "GTIN" },
  { ai: '02', kind: 'gtin', len: 14, checkDigit: true, req: [['37']], ex: ['01', '03'], group: 'identification', title: "CONTENT" },
  { ai: '03', kind: 'gtin', len: 14, checkDigit: true, ex: ['01', '02', '37'], group: 'identification', title: "MTO GTIN" },
  { ai: '10', kind: 'varAlnum', len: 20, req: [['01'], ['02'], ['03'], ['8006'], ['8026']], group: 'batchQty', title: "BATCH/LOT" },
  { ai: '11', kind: 'date', len: 6, day00: true, req: [['01'], ['02'], ['03'], ['8006'], ['8026']], group: 'date', title: "PROD DATE" },
  { ai: '12', kind: 'date', len: 6, day00: true, req: [['8020']], group: 'date', title: "DUE DATE" },
  { ai: '13', kind: 'date', len: 6, day00: true, req: [['01'], ['02'], ['03'], ['8006'], ['8026']], group: 'date', title: "PACK DATE" },
  { ai: '15', kind: 'date', len: 6, day00: true, req: [['01'], ['02'], ['03'], ['8006'], ['8026']], group: 'date', title: "BEST BEFORE or BEST BY" },
  { ai: '16', kind: 'date', len: 6, day00: true, req: [['01'], ['02'], ['03'], ['8006'], ['8026']], group: 'date', title: "SELL BY" },
  { ai: '17', kind: 'date', len: 6, day00: true, req: [['01'], ['02'], ['03'], ['255'], ['8006'], ['8026']], group: 'date', title: "USE BY or EXPIRY" },
  { ai: '20', kind: 'fixedNum', len: 2, req: [['01'], ['02'], ['8006'], ['8026']], group: 'batchQty', title: "VARIANT" },
  { ai: '21', kind: 'varAlnum', len: 20, req: [['01'], ['03'], ['8006']], ex: ['235'], group: 'identification', title: "SERIAL" },
  { ai: '22', kind: 'varAlnum', len: 20, req: [['01']], group: 'identification', title: "CPV" },
  { ai: '235', kind: 'varAlnum', len: 28, req: [['01']], group: 'identification', title: "TPX" },
  { ai: '240', kind: 'varAlnum', len: 30, req: [['01'], ['02'], ['8006'], ['8026']], group: 'identification', title: "ADDITIONAL ID" },
  { ai: '241', kind: 'varAlnum', len: 30, req: [['01'], ['02'], ['8006'], ['8026']], group: 'identification', title: "CUST. PART No." },
  { ai: '242', kind: 'varNum', len: 6, req: [['01'], ['02'], ['8006'], ['8026']], group: 'identification', title: "MTO VARIANT" },
  { ai: '243', kind: 'varAlnum', len: 20, req: [['01']], group: 'identification', title: "PCN" },
  { ai: '250', kind: 'varAlnum', len: 30, req: [['01', '21'], ['8006', '21']], group: 'identification', title: "SECONDARY SERIAL" },
  { ai: '251', kind: 'varAlnum', len: 30, req: [['01'], ['8006']], group: 'identification', title: "REF. TO SOURCE" },
  { ai: '253', kind: 'fixedNum', len: 13, checkDigit: true, multiComponent: true, group: 'identification', title: "GDTI" },
  { ai: '254', kind: 'varAlnum', len: 20, req: [['414']], group: 'identification', title: "GLN EXTENSION COMPONENT" },
  { ai: '255', kind: 'fixedNum', len: 13, checkDigit: true, ex: ['01', '02', '415', '8006', '8020', '8026'], multiComponent: true, group: 'identification', title: "GCN" },
  { ai: '30', kind: 'varNum', len: 8, req: [['01'], ['02']], group: 'batchQty', title: "VAR. COUNT" },
  { ai: '3100-3105', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['310n'], group: 'measures', title: "NET WEIGHT (kg)" },
  { ai: '3110-3115', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['311n'], group: 'measures', title: "LENGTH (m)" },
  { ai: '3120-3125', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['312n'], group: 'measures', title: "WIDTH (m)" },
  { ai: '3130-3135', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['313n'], group: 'measures', title: "HEIGHT (m)" },
  { ai: '3140-3145', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['314n'], group: 'measures', title: "AREA (m²)" },
  { ai: '3150-3155', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['315n'], group: 'measures', title: "NET VOLUME (l)" },
  { ai: '3160-3165', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['316n'], group: 'measures', title: "NET VOLUME (m³)" },
  { ai: '3200-3205', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['320n'], group: 'measures', title: "NET WEIGHT (lb)" },
  { ai: '3210-3215', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['321n'], group: 'measures', title: "LENGTH (in)" },
  { ai: '3220-3225', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['322n'], group: 'measures', title: "LENGTH (ft)" },
  { ai: '3230-3235', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['323n'], group: 'measures', title: "LENGTH (yd)" },
  { ai: '3240-3245', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['324n'], group: 'measures', title: "WIDTH (in)" },
  { ai: '3250-3255', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['325n'], group: 'measures', title: "WIDTH (ft)" },
  { ai: '3260-3265', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['326n'], group: 'measures', title: "WIDTH (yd)" },
  { ai: '3270-3275', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['327n'], group: 'measures', title: "HEIGHT (in)" },
  { ai: '3280-3285', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['328n'], group: 'measures', title: "HEIGHT (ft)" },
  { ai: '3290-3295', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['329n'], group: 'measures', title: "HEIGHT (yd)" },
  { ai: '3300-3305', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['330n'], group: 'measures', title: "GROSS WEIGHT (kg)" },
  { ai: '3310-3315', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['331n'], group: 'measures', title: "LENGTH (m), log" },
  { ai: '3320-3325', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['332n'], group: 'measures', title: "WIDTH (m), log" },
  { ai: '3330-3335', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['333n'], group: 'measures', title: "HEIGHT (m), log" },
  { ai: '3340-3345', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['334n'], group: 'measures', title: "AREA (m²), log" },
  { ai: '3350-3355', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['335n'], group: 'measures', title: "VOLUME (l), log" },
  { ai: '3360-3365', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['336n'], group: 'measures', title: "VOLUME (m³), log" },
  { ai: '3370-3375', kind: 'decimal', len: 6, req: [['01']], ex: ['337n'], group: 'measures', title: "KG PER m²" },
  { ai: '3400-3405', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['340n'], group: 'measures', title: "GROSS WEIGHT (lb)" },
  { ai: '3410-3415', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['341n'], group: 'measures', title: "LENGTH (in), log" },
  { ai: '3420-3425', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['342n'], group: 'measures', title: "LENGTH (ft), log" },
  { ai: '3430-3435', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['343n'], group: 'measures', title: "LENGTH (yd), log" },
  { ai: '3440-3445', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['344n'], group: 'measures', title: "WIDTH (in), log" },
  { ai: '3450-3455', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['345n'], group: 'measures', title: "WIDTH (ft), log" },
  { ai: '3460-3465', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['346n'], group: 'measures', title: "WIDTH (yd), log" },
  { ai: '3470-3475', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['347n'], group: 'measures', title: "HEIGHT (in), log" },
  { ai: '3480-3485', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['348n'], group: 'measures', title: "HEIGHT (ft), log" },
  { ai: '3490-3495', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['349n'], group: 'measures', title: "HEIGHT (yd), log" },
  { ai: '3500-3505', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['350n'], group: 'measures', title: "AREA (in²)" },
  { ai: '3510-3515', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['351n'], group: 'measures', title: "AREA (ft²)" },
  { ai: '3520-3525', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['352n'], group: 'measures', title: "AREA (yd²)" },
  { ai: '3530-3535', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['353n'], group: 'measures', title: "AREA (in²), log" },
  { ai: '3540-3545', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['354n'], group: 'measures', title: "AREA (ft²), log" },
  { ai: '3550-3555', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['355n'], group: 'measures', title: "AREA (yd²), log" },
  { ai: '3560-3565', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['356n'], group: 'measures', title: "NET WEIGHT (tr oz)" },
  { ai: '3570-3575', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['357n'], group: 'measures', title: "NET VOLUME (oz)" },
  { ai: '3600-3605', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['360n'], group: 'measures', title: "NET VOLUME (qt (US))" },
  { ai: '3610-3615', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['361n'], group: 'measures', title: "NET VOLUME (gal.)" },
  { ai: '3620-3625', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['362n'], group: 'measures', title: "VOLUME (qt (US)), log" },
  { ai: '3630-3635', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['363n'], group: 'measures', title: "VOLUME (gal (US)), log" },
  { ai: '3640-3645', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['364n'], group: 'measures', title: "NET VOLUME (in³)" },
  { ai: '3650-3655', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['365n'], group: 'measures', title: "NET VOLUME (ft³)" },
  { ai: '3660-3665', kind: 'decimal', len: 6, req: [['01'], ['02']], ex: ['366n'], group: 'measures', title: "NET VOLUME (yd³)" },
  { ai: '3670-3675', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['367n'], group: 'measures', title: "VOLUME (in³), log" },
  { ai: '3680-3685', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['368n'], group: 'measures', title: "VOLUME (ft³), log" },
  { ai: '3690-3695', kind: 'decimal', len: 6, req: [['00'], ['01']], ex: ['369n'], group: 'measures', title: "VOLUME (yd³), log" },
  { ai: '37', kind: 'varNum', len: 8, req: [['00', '02'], ['00', '8026']], group: 'batchQty', title: "COUNT" },
  { ai: '3900-3909', kind: 'varNum', len: 15, req: [['255'], ['8020']], ex: ['390n', '391n', '394n', '8111'], group: 'batchQty', title: "AMOUNT" },
  { ai: '3910-3919', kind: 'fixedNum', len: 3, req: [['8020']], ex: ['391n'], multiComponent: true, group: 'batchQty', title: "AMOUNT" },
  { ai: '3920-3929', kind: 'varNum', len: 15, req: [['01', '30'], ['01', '31nn'], ['01', '32nn'], ['01', '35nn'], ['01', '36nn']], ex: ['392n', '393n'], group: 'batchQty', title: "PRICE" },
  { ai: '3930-3939', kind: 'fixedNum', len: 3, req: [['30'], ['31nn'], ['32nn'], ['35nn'], ['36nn']], ex: ['393n'], multiComponent: true, group: 'batchQty', title: "PRICE" },
  { ai: '3940-3943', kind: 'fixedNum', len: 4, req: [['255']], ex: ['394n', '8111'], group: 'batchQty', title: "PRCNT OFF" },
  { ai: '3950-3955', kind: 'fixedNum', len: 6, req: [['30'], ['31nn'], ['32nn'], ['35nn'], ['36nn']], ex: ['392n', '393n', '395n', '8005'], group: 'batchQty', title: "PRICE/UoM" },
  { ai: '400', kind: 'varAlnum', len: 30, group: 'logistics', title: "ORDER NUMBER" },
  { ai: '401', kind: 'varAlnum', len: 30, group: 'logistics', title: "GINC" },
  { ai: '402', kind: 'fixedNum', len: 17, checkDigit: true, group: 'logistics', title: "GSIN" },
  { ai: '403', kind: 'varAlnum', len: 30, req: [['00']], group: 'logistics', title: "ROUTE" },
  { ai: '410', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "SHIP TO LOC" },
  { ai: '411', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "BILL TO" },
  { ai: '412', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "PURCHASE FROM" },
  { ai: '413', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "SHIP FOR LOC" },
  { ai: '414', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "LOC No." },
  { ai: '415', kind: 'fixedNum', len: 13, checkDigit: true, req: [['8020']], group: 'logistics', title: "PAY TO" },
  { ai: '416', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "PROD/SERV LOC" },
  { ai: '417', kind: 'fixedNum', len: 13, checkDigit: true, group: 'logistics', title: "PARTY" },
  { ai: '420', kind: 'varAlnum', len: 20, ex: ['421'], group: 'logistics', title: "SHIP TO POST" },
  { ai: '421', kind: 'fixedNum', len: 3, ex: ['4307'], multiComponent: true, group: 'logistics', title: "SHIP TO POST" },
  { ai: '422', kind: 'fixedNum', len: 3, req: [['01'], ['02'], ['8006'], ['8026']], ex: ['426'], group: 'logistics', title: "ORIGIN" },
  { ai: '423', kind: 'fixedNum', len: 3, req: [['01'], ['02']], ex: ['426'], multiComponent: true, group: 'logistics', title: "COUNTRY - INITIAL PROCESS" },
  { ai: '424', kind: 'fixedNum', len: 3, req: [['01'], ['02']], ex: ['426'], group: 'logistics', title: "COUNTRY - PROCESS" },
  { ai: '425', kind: 'fixedNum', len: 3, req: [['01'], ['02']], ex: ['426'], multiComponent: true, group: 'logistics', title: "COUNTRY - DISASSEMBLY" },
  { ai: '426', kind: 'fixedNum', len: 3, req: [['01'], ['02']], group: 'logistics', title: "COUNTRY - FULL PROCESS" },
  { ai: '427', kind: 'varAlnum', len: 3, req: [['01', '422'], ['02', '422']], group: 'logistics', title: "ORIGIN SUBDIVISION" },
  { ai: '4300', kind: 'varAlnum', len: 35, req: [['00']], group: 'logistics', title: "SHIP TO COMP" },
  { ai: '4301', kind: 'varAlnum', len: 35, req: [['00']], group: 'logistics', title: "SHIP TO NAME" },
  { ai: '4302', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "SHIP TO ADD1" },
  { ai: '4303', kind: 'varAlnum', len: 70, req: [['4302']], group: 'logistics', title: "SHIP TO ADD2" },
  { ai: '4304', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "SHIP TO SUB" },
  { ai: '4305', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "SHIP TO LOC" },
  { ai: '4306', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "SHIP TO REG" },
  { ai: '4307', kind: 'fixedAlnum', len: 2, linters: ['iso3166alpha2'], req: [['00']], group: 'logistics', title: "SHIP TO COUNTRY" },
  { ai: '4308', kind: 'varAlnum', len: 30, req: [['00']], group: 'logistics', title: "SHIP TO PHONE" },
  { ai: '4309', kind: 'fixedNum', len: 10, req: [['00']], multiComponent: true, group: 'logistics', title: "SHIP TO GEO" },
  { ai: '4310', kind: 'varAlnum', len: 35, req: [['00']], group: 'logistics', title: "RTN TO COMP" },
  { ai: '4311', kind: 'varAlnum', len: 35, req: [['00']], group: 'logistics', title: "RTN TO NAME" },
  { ai: '4312', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "RTN TO ADD1" },
  { ai: '4313', kind: 'varAlnum', len: 70, req: [['4312']], group: 'logistics', title: "RTN TO ADD2" },
  { ai: '4314', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "RTN TO SUB" },
  { ai: '4315', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "RTN TO LOC" },
  { ai: '4316', kind: 'varAlnum', len: 70, req: [['00']], group: 'logistics', title: "RTN TO REG" },
  { ai: '4317', kind: 'fixedAlnum', len: 2, linters: ['iso3166alpha2'], req: [['00']], group: 'logistics', title: "RTN TO COUNTRY" },
  { ai: '4318', kind: 'varAlnum', len: 20, req: [['00']], group: 'logistics', title: "RTN TO POST" },
  { ai: '4319', kind: 'varAlnum', len: 30, req: [['00']], group: 'logistics', title: "RTN TO PHONE" },
  { ai: '4320', kind: 'varAlnum', len: 35, req: [['00']], group: 'logistics', title: "SRV DESCRIPTION" },
  { ai: '4321', kind: 'fixedNum', len: 1, linters: ['yesno'], req: [['00']], group: 'logistics', title: "DANGEROUS GOODS" },
  { ai: '4322', kind: 'fixedNum', len: 1, linters: ['yesno'], req: [['00']], group: 'logistics', title: "AUTH TO LEAVE" },
  { ai: '4323', kind: 'fixedNum', len: 1, linters: ['yesno'], req: [['00']], group: 'logistics', title: "SIG REQUIRED" },
  { ai: '4324', kind: 'date', len: 6, day00: true, req: [['00']], multiComponent: true, group: 'logistics', title: "NOT BEF DEL DT" },
  { ai: '4325', kind: 'date', len: 6, day00: true, req: [['00']], multiComponent: true, group: 'logistics', title: "NOT AFT DEL DT" },
  { ai: '4326', kind: 'date', len: 6, req: [['00']], group: 'logistics', title: "REL DATE" },
  { ai: '4330', kind: 'fixedNum', len: 6, req: [['00']], ex: ['4331'], multiComponent: true, group: 'logistics', title: "MAX TEMP F." },
  { ai: '4331', kind: 'fixedNum', len: 6, req: [['00']], ex: ['4330'], multiComponent: true, group: 'logistics', title: "MAX TEMP C." },
  { ai: '4332', kind: 'fixedNum', len: 6, req: [['00']], ex: ['4333'], multiComponent: true, group: 'logistics', title: "MIN TEMP F." },
  { ai: '4333', kind: 'fixedNum', len: 6, req: [['00']], ex: ['4332'], multiComponent: true, group: 'logistics', title: "MIN TEMP C." },
  { ai: '7001', kind: 'fixedNum', len: 13, req: [['01'], ['02'], ['8006'], ['8026']], group: 'logistics', title: "NSN" },
  { ai: '7002', kind: 'varAlnum', len: 30, req: [['01'], ['02']], group: 'logistics', title: "MEAT CUT" },
  { ai: '7003', kind: 'date', len: 6, req: [['01'], ['02']], multiComponent: true, group: 'date', title: "EXPIRY TIME" },
  { ai: '7004', kind: 'varNum', len: 4, req: [['01', '10']], group: 'logistics', title: "ACTIVE POTENCY" },
  { ai: '7005', kind: 'varAlnum', len: 12, req: [['01'], ['02']], group: 'logistics', title: "CATCH AREA" },
  { ai: '7006', kind: 'date', len: 6, req: [['01'], ['02']], group: 'date', title: "FIRST FREEZE DATE" },
  { ai: '7007', kind: 'date', len: 6, req: [['01'], ['02']], multiComponent: true, group: 'date', title: "HARVEST DATE" },
  { ai: '7008', kind: 'varAlnum', len: 3, req: [['01'], ['02']], group: 'logistics', title: "AQUATIC SPECIES" },
  { ai: '7009', kind: 'varAlnum', len: 10, req: [['01'], ['02']], group: 'logistics', title: "FISHING GEAR TYPE" },
  { ai: '7010', kind: 'varAlnum', len: 2, req: [['01'], ['02']], group: 'logistics', title: "PROD METHOD" },
  { ai: '7011', kind: 'date', len: 6, req: [['01'], ['02']], multiComponent: true, group: 'date', title: "TEST BY DATE" },
  { ai: '7020', kind: 'varAlnum', len: 20, req: [['01', '416'], ['8006', '416']], group: 'logistics', title: "REFURB LOT" },
  { ai: '7021', kind: 'varAlnum', len: 20, req: [['01'], ['8006']], group: 'logistics', title: "FUNC STAT" },
  { ai: '7022', kind: 'varAlnum', len: 20, req: [['7021']], group: 'logistics', title: "REV STAT" },
  { ai: '7023', kind: 'varAlnum', len: 30, group: 'logistics', title: "GIAI - ASSEMBLY" },
  { ai: '7030', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 0" },
  { ai: '7031', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 1" },
  { ai: '7032', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 2" },
  { ai: '7033', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 3" },
  { ai: '7034', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 4" },
  { ai: '7035', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 5" },
  { ai: '7036', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 6" },
  { ai: '7037', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 7" },
  { ai: '7038', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 8" },
  { ai: '7039', kind: 'fixedNum', len: 3, req: [['01'], ['02']], multiComponent: true, group: 'logistics', title: "PROCESSOR # 9" },
  { ai: '7040', kind: 'fixedNum', len: 1, multiComponent: true, group: 'logistics', title: "UIC+EXT" },
  { ai: '7041', kind: 'varAlnum', len: 4, req: [['00']], group: 'logistics', title: "UFRGT UNIT TYPE" },
  { ai: '710', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN PZN" },
  { ai: '711', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN CIP" },
  { ai: '712', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN CN" },
  { ai: '713', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN DRN" },
  { ai: '714', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN AIM" },
  { ai: '715', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN NDC" },
  { ai: '716', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN AIC" },
  { ai: '717', kind: 'varAlnum', len: 20, req: [['01']], group: 'attributes', title: "NHRN SRN" },
  { ai: '7230', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 1" },
  { ai: '7231', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 2" },
  { ai: '7232', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 3" },
  { ai: '7233', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 4" },
  { ai: '7234', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 5" },
  { ai: '7235', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 6" },
  { ai: '7236', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 7" },
  { ai: '7237', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 8" },
  { ai: '7238', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 9" },
  { ai: '7239', kind: 'fixedAlnum', len: 2, req: [['01'], ['8004']], multiComponent: true, group: 'attributes', title: "CERT # 10" },
  { ai: '7240', kind: 'varAlnum', len: 20, req: [['01'], ['8006']], group: 'attributes', title: "PROTOCOL" },
  { ai: '7241', kind: 'fixedNum', len: 2, req: [['8017'], ['8018']], group: 'attributes', title: "AIDC MEDIA TYPE" },
  { ai: '7242', kind: 'varAlnum', len: 25, req: [['8017'], ['8018']], group: 'attributes', title: "VCN" },
  { ai: '7250', kind: 'date', len: 8, req: [['8018']], ex: ['7251'], group: 'attributes', title: "DOB" },
  { ai: '7251', kind: 'date', len: 8, req: [['8018']], ex: ['7250'], multiComponent: true, group: 'attributes', title: "DOB TIME" },
  { ai: '7252', kind: 'fixedNum', len: 1, req: [['8018']], group: 'attributes', title: "BIO SEX" },
  { ai: '7253', kind: 'varAlnum', len: 40, req: [['8017'], ['8018']], ex: ['7256', '7259'], group: 'attributes', title: "FAMILY NAME" },
  { ai: '7254', kind: 'varAlnum', len: 40, req: [['8017'], ['8018']], ex: ['7256', '7259'], group: 'attributes', title: "GIVEN NAME" },
  { ai: '7255', kind: 'varAlnum', len: 10, req: [['8017'], ['8018']], ex: ['7256', '7259'], group: 'attributes', title: "SUFFIX" },
  { ai: '7256', kind: 'varAlnum', len: 90, req: [['8017'], ['8018']], group: 'attributes', title: "FULL NAME" },
  { ai: '7257', kind: 'varAlnum', len: 70, req: [['8018']], group: 'attributes', title: "PERSON ADDR" },
  { ai: '7258', kind: 'fixedAlnum', len: 3, req: [['8018', '7259']], group: 'attributes', title: "BIRTH SEQUENCE" },
  { ai: '7259', kind: 'varAlnum', len: 40, req: [['8018']], ex: ['7256'], group: 'attributes', title: "BABY" },
  { ai: '8001', kind: 'fixedNum', len: 4, req: [['01']], multiComponent: true, group: 'identification', title: "DIMENSIONS" },
  { ai: '8002', kind: 'varAlnum', len: 20, group: 'attributes', title: "CMT No." },
  { ai: '8003', kind: 'fixedNum', len: 1, multiComponent: true, group: 'identification', title: "GRAI" },
  { ai: '8004', kind: 'varAlnum', len: 30, group: 'identification', title: "GIAI" },
  { ai: '8005', kind: 'fixedNum', len: 6, req: [['01'], ['02']], group: 'batchQty', title: "PRICE PER UNIT" },
  { ai: '8006', kind: 'fixedNum', len: 14, checkDigit: true, ex: ['01', '37'], multiComponent: true, group: 'identification', title: "ITIP" },
  { ai: '8007', kind: 'varAlnum', len: 34, req: [['415']], group: 'attributes', title: "IBAN" },
  { ai: '8008', kind: 'date', len: 6, req: [['01'], ['02']], multiComponent: true, group: 'date', title: "PROD TIME" },
  { ai: '8009', kind: 'varAlnum', len: 50, req: [['00'], ['01']], group: 'attributes', title: "OPTSEN" },
  { ai: '8010', kind: 'varAlnum', len: 30, linters: ['cset39'], group: 'identification', title: "CPID" },
  { ai: '8011', kind: 'varNum', len: 12, req: [['8010']], group: 'batchQty', title: "CPID SERIAL" },
  { ai: '8012', kind: 'varAlnum', len: 20, req: [['01'], ['8006']], group: 'batchQty', title: "VERSION" },
  { ai: '8013', kind: 'varAlnum', len: 25, linters: ['csumalpha'], group: 'identification', title: "GMN" },
  { ai: '8014', kind: 'varAlnum', len: 25, linters: ['csumalpha'], req: [['01']], group: 'attributes', title: "MUDI" },
  { ai: '8017', kind: 'fixedNum', len: 18, checkDigit: true, ex: ['8018'], group: 'identification', title: "GSRN - PROVIDER" },
  { ai: '8018', kind: 'fixedNum', len: 18, checkDigit: true, ex: ['8017'], group: 'identification', title: "GSRN - RECIPIENT" },
  { ai: '8019', kind: 'varNum', len: 10, req: [['8017'], ['8018']], group: 'identification', title: "SRIN" },
  { ai: '8020', kind: 'varAlnum', len: 25, req: [['415']], group: 'batchQty', title: "REF No." },
  { ai: '8026', kind: 'fixedNum', len: 14, checkDigit: true, req: [['37']], ex: ['02', '8006'], multiComponent: true, group: 'identification', title: "ITIP CONTENT" },
  { ai: '8030', kind: 'varAlnum', len: 90, linters: ['cset64'], req: [['00'], ['01', '21'], ['253'], ['255'], ['8003'], ['8004'], ['8006', '21'], ['8010', '8011'], ['8017'], ['8018']], group: 'attributes', title: "DIGSIG" },
  { ai: '8040', kind: 'fixedNum', len: 15, req: [['01', '21']], group: 'attributes', title: "IMEI" },
  { ai: '8041', kind: 'fixedNum', len: 15, req: [['01', '21', '8040']], group: 'attributes', title: "IMEI2" },
  { ai: '8042', kind: 'fixedNum', len: 32, req: [['01', '21', '8040']], group: 'attributes', title: "ESIM" },
  { ai: '8043', kind: 'fixedNum', len: 18, req: [['01', '21', '8040']], multiComponent: true, group: 'attributes', title: "PSIM" },
  { ai: '8110', kind: 'varAlnum', len: 70, group: 'attributes', title: "" },
  { ai: '8111', kind: 'fixedNum', len: 4, req: [['255']], group: 'attributes', title: "POINTS" },
  { ai: '8112', kind: 'varAlnum', len: 70, group: 'attributes', title: "" },
  { ai: '8200', kind: 'varAlnum', len: 70, req: [['01']], group: 'url', title: "PRODUCT URL" },
  { ai: '90', kind: 'varAlnum', len: 30, group: 'internal', title: "INTERNAL" },
  { ai: '91-99', kind: 'varAlnum', len: 90, group: 'internal', title: "INTERNAL" },
];
